@baseUrl = http://127.0.0.1:8000

###
# @name AllStates
GET {{baseUrl}}/api/states

###
# @name CreateState
POST {{baseUrl}}/api/states/
Content-Type: application/json

{
    "name": "Santa Catarina",
    "abbreviation": "SC"
}


###
# @name StateOne
GET {{baseUrl}}/api/states/2

###
# @name StateDelete
DELETE {{baseUrl}}/api/states/1


###
# @name StateUpdate
PUT {{baseUrl}}/api/states/6
Content-Type: application/json

{
    "name": "Para",
    "abbreviation": "PA"
}