@baseUrl = http://127.0.0.1:8000

###
# @name All
GET {{baseUrl}}/api/cities
###
# @name Create
POST {{baseUrl}}/api/cities/
Content-Type: application/json

{
    "name": "Uberlandia",
    "state_id": 8
}


###
# @name CityOne
GET {{baseUrl}}/api/cities/6

###
# @name CityDelete
DELETE {{baseUrl}}/api/cities/20


###
# @name StateUpdate
PUT {{baseUrl}}/api/cities/30
Content-Type: application/json

{
    "name": "Palmas"
}