@baseUrl = http://127.0.0.1:8000

###
# @name All
GET {{baseUrl}}/api/legalpeople

###
# @name CreateLegalPeople
POST {{baseUrl}}/api/legalpeople/
Content-Type: application/json

{
    "fantasy_name": "Pacific Security LTDA",
    "cnpj": "21.326.021/0001-71",
    "city_id": 12
}


###
# @name One
GET {{baseUrl}}/api/legalpeople/2

###
# @name LegalPeopleDelete
DELETE {{baseUrl}}/api/legalpeople/20


###
# @name Update
PUT {{baseUrl}}/api/legalpeople/5
Content-Type: application/json

{
    "city_id": 11
}