@baseUrl = http://127.0.0.1:8000

###
# @name All
GET {{baseUrl}}/api/naturalpeople

###
# @name Create
POST {{baseUrl}}/api/naturalpeople/
Content-Type: application/json

{
    "name": "Samela augusta rocha",
    "cpf": "45684938492",
    "city_id": 12
}


###
# @name One
GET {{baseUrl}}/api/naturalpeople/2

###
# @name Delete
DELETE {{baseUrl}}/api/naturalpeople/20


###
# @name Update
PUT {{baseUrl}}/api/naturalpeople/2
Content-Type: application/json

{
    "city_id": 11
}