@baseUrl = http://127.0.0.1:8000
@resource = packages


###
# @name All
GET {{baseUrl}}/api/{{resource}}

###
# @name Create
POST {{baseUrl}}/api/{{resource}}/
Content-Type: application/json

{
    "name": "Acre",
    "abbreviation": "AC"
}


###
# @name One
GET {{baseUrl}}/api/{{resource}}/2

###
# @name Delete
DELETE {{baseUrl}}/api/{{resource}}/5

###
# @name Update
PUT {{baseUrl}}/api/{{resource}}/2
Content-Type: application/json

{
    "name": "Tocantins",
    "abbreviation": "TO"
}