@baseUrl = http://127.0.0.1:8000

###
# @name All
GET {{baseUrl}}/api/states

###
# @name Create
POST {{baseUrl}}/api/states/
Content-Type: application/json

{
    "name": "Minas gerais",
    "abbreviation": "MG"
}


###
# @name One
GET {{baseUrl}}/api/states/2

###
# @name Delete
DELETE {{baseUrl}}/api/states/5

###
# @name Update
PUT {{baseUrl}}/api/states/2
Content-Type: application/json

{
    "name": "Tocantins",
    "abbreviation": "TO"
}