# Generated by Django 3.2 on 2024-02-01 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nome')),
                ('abbreviation', models.CharField(max_length=2, unique=True, verbose_name='Sigla')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nome')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='tracker.state')),
            ],
        ),
    ]
